# Generated by Django 4.2.9 on 2024-01-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="conclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("urgente", "Urgente"),
                    ("importante", "Importante"),
                    ("comum", "Comum"),
                ],
                default="comum",
                max_length=25,
            ),
        ),
    ]
