# Generated by Django 4.2.9 on 2024-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_tarefa_conclusao_alter_tarefa_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="prazo",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluída", "Concluída"),
                    ("pendente", "Pendente"),
                    ("adiada", "Adiada"),
                ],
                default="pendente",
                max_length=25,
            ),
        ),
    ]
