# Generated by Django 4.2.9 on 2024-02-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0003_tarefa_prazo_alter_tarefa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="dia_restante",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
